[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-sys-tuner"
description = "The solana cluster system tuner daemon"
version = "1.13.603"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-sys-tuner"
publish = true

[dependencies]
clap = "2.33.1"
libc = "0.2.120"
log = "0.4.14"
solana-logger = { path = "../logger", version = "=1.13.603" }
solana-version = { path = "../version", version = "=1.13.603" }

[target."cfg(unix)".dependencies]
unix_socket2 = "0.5.4"
users = "0.10.0"
nix = "0.23.1"
sysctl = "0.4.4"

[lib]
name = "solana_sys_tuner"

[[bin]]
name = "solana-sys-tuner"
path = "src/main.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
