[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-replica-lib"
description = "The library used for replication by both the client and server"
version = "1.13.603"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-validator"

[dependencies]
crossbeam-channel = "0.5"
futures-util = "0.3"
log = "0.4.11"
prost = "0.10.0"
solana-rpc = { path = "../rpc", version = "=1.13.603" }
solana-runtime = { path = "../runtime", version = "=1.13.603" }
solana-sdk = { path = "../sdk", version = "=1.13.603" }
tokio = { version = "~1.14.1", features = ["full"] }
tonic = { version = "0.7.1", features = ["tls", "transport"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
tonic-build = "0.7.0"
