[package]
name = "solana-program"
version = "1.13.603"
description = "Solana Program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-program"
readme = "README.md"
license = "Apache-2.0"
edition = "2021"

[dependencies]
bincode = "1.3.1"
blake3 = { version = "1.2.0", features = ["traits-preview"] }
borsh = "0.9.1"
borsh-derive = "0.9.1"
bs58 = "0.4.0"
bytemuck = { version = "1.7.2", features = ["derive"] }
bv = { version = "0.11.1", features = ["serde"] }
itertools =  "0.10.1"
fast-math = "0.1"
hex = { version = "0.4.3", features = ["serde"] }
lazy_static = "1.4.0"
log = "0.4.14"
num-derive = "0.3"
num-traits = "0.2"
pythnet-sdk = { git = "https://github.com/pyth-network/pyth-crosschain", version = "1.13.6", rev = "e670f57f89b05398ca352e4accb1e32724a8e1b4" }
rustversion = "1.0.3"
serde = "1.0.112"
schemars = "0.8.8"
serde_bytes = "0.11"
serde_derive = "1.0.103"
sha2 = "0.10.0"
sha3 = "0.10.0"
solana-frozen-abi = { path = "../../frozen-abi", version = "=1.13.603" }
solana-frozen-abi-macro = { path = "../../frozen-abi/macro", version = "=1.13.603" }
solana-sdk-macro = { path = "../macro", version = "=1.13.603" }
thiserror = "1.0"

[target.'cfg(not(target_arch = "bpf"))'.dependencies]
bitflags = "1.3.1"
base64 = "0.13"
curve25519-dalek = "3.2.1"
libsecp256k1 = "0.6.0"
rand = "0.7.0"
itertools = "0.10.1"
wasm-bindgen = "0.2"

[target.'cfg(not(target_arch = "bpf"))'.dev-dependencies]
solana-logger = { path = "../../logger", version = "=1.13.603" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.7"
console_log = "0.2.0"
js-sys = "0.3.55"
getrandom = { version = "0.1", features = ["wasm-bindgen"] }

[target.'cfg(not(target_pointer_width = "64"))'.dependencies]
parking_lot = "0.12"

[dev-dependencies]
anyhow = "1.0.45"
assert_matches = "1.3.0"
bincode = "1.3.1"
borsh = "0.9.1"
borsh-derive = "0.9.1"
serde_json = "1.0.56"
static_assertions = "1.1.0"

[build-dependencies]
rustc_version = "0.4"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[lib]
crate-type = ["cdylib", "rlib"]
