[package]
name = "solana-streamer"
version = "1.15.0"
description = "Solana Streamer"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-streamer"
edition = "2021"

[dependencies]
crossbeam-channel = "0.5"
futures-util = "0.3.25"
histogram = "0.6.9"
indexmap = "1.9.1"
itertools = "0.10.5"
libc = "0.2.131"
log = "0.4.17"
nix = "0.26.2"
pem = "1.1.1"
percentage = "0.1.0"
pkcs8 = { version = "0.8.0", features = ["alloc"] }
quinn = "0.9.3"
quinn-proto = "0.9.2"
quinn-udp = "0.3.2"

rand = "0.7.0"
rcgen = "0.10.0"
rustls = { version = "0.20.6", default-features = false, features = ["dangerous_configuration", "logging"] }
solana-metrics = { path = "../metrics", version = "=1.15.0" }
solana-perf = { path = "../perf", version = "=1.15.0" }
solana-sdk = { path = "../sdk", version = "=1.15.0" }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
x509-parser = "0.14.0"

[dev-dependencies]
solana-logger = { path = "../logger", version = "=1.15.0" }

[lib]
crate-type = ["lib"]
name = "solana_streamer"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
