name: Test Updated Pythnet Node
on:
  workflow_dispatch:
    inputs:
      node:
        required: true
        type: choice
        description: Which Pythnet node to upgrade
        options:
          - 1
          - 2
      tag:
        required: true
        type: string
jobs:
  update-node:
    name: Pythnet Node Updater
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout tag
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@8a84b07f2009032ade05a88a28750d733cc30db1
        with:
          role-to-assume: 'arn:aws:iam::192824654885:role/github-pythnet-updater'
          aws-region: eu-west-2
      - name: Zip directory
        run: zip -r -q pythnet.zip .
      - name: Create temp key for SSH
        run: ssh-keygen -t rsa -f temp_key
      - name: Send key to instance
        run: aws ec2-instance-connect send-ssh-public-key \
                --instance-id i-001234a4bf70dec41EXAMPLE \
                --availability-zone eu-west-2a \
                --instance-os-user ubuntu \
                --ssh-public-key file://temp_key.pub
